# Generated by Django 4.2.4 on 2023-09-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=2023, upload_to='media/product_images'),
            preserve_default=False,
        ),
    ]
