# Generated by Django 4.2.4 on 2023-09-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to='media/product_images', verbose_name='product_image'),
        ),
    ]
